import * as dependencyCruiser from 'dependency-cruiser';
import type { EnforcerPort, EnforcerConfig, CheckResult, Violation } from '../../core/ports/ports.js';
import type { BoundaryModel } from '../../core/model/boundary-model.js';

// dependency-cruiser ships CommonJS; reach `cruise` through either interop shape.
const cruise: (
  files: string[],
  options: unknown,
) => Promise<{ output: unknown; exitCode: number }> =
  (dependencyCruiser as any).cruise ?? (dependencyCruiser as any).default?.cruise;

interface ForbiddenRule {
  name: string;
  comment: string;
  severity: 'error';
  from: { path: string };
  to: { path: string[] };
}

function folderToRegex(folder: string): string {
  const normalized = folder.replace(/\/+$/, '');
  const escaped = normalized.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return `^${escaped}/`;
}

/**
 * Derives one forbidden rule per module: files in the module may not import any
 * other module's folder unless the diagram allows that edge. Dependencies into
 * non-module paths (node_modules, unmapped folders) are left untouched — the
 * architecture only governs edges it drew.
 */
function buildForbiddenRules(model: BoundaryModel): ForbiddenRule[] {
  const allowedTargets = new Map<string, Set<string>>();
  for (const m of model.modules) allowedTargets.set(m.id, new Set([m.id]));
  for (const edge of model.allowed) allowedTargets.get(edge.from)?.add(edge.to);

  const rules: ForbiddenRule[] = [];
  for (const m of model.modules) {
    const allowed = allowedTargets.get(m.id)!;
    const forbidden = model.modules.filter((t) => !allowed.has(t.id));
    if (forbidden.length === 0) continue;
    rules.push({
      name: `boundary-${m.id}`,
      comment: `${m.title} may only depend on: ${[...allowed].sort().join(', ')}`,
      severity: 'error',
      from: { path: folderToRegex(m.folder) },
      to: { path: forbidden.map((t) => folderToRegex(t.folder)) },
    });
  }
  return rules;
}

/** First enforcer adapter: targets dependency-cruiser for TypeScript. */
export class DepCruiserEnforcer implements EnforcerPort {
  render(model: BoundaryModel): EnforcerConfig {
    const forbidden = buildForbiddenRules(model);
    const content = `/** Generated by Boundry from the architecture diagram. Do not edit by hand. */
module.exports = {
  forbidden: ${JSON.stringify(forbidden, null, 2)},
  options: {
    doNotFollow: { path: 'node_modules' },
    tsPreCompilationDeps: true,
  },
};
`;
    return { filename: '.dependency-cruiser.cjs', content };
  }

  async check(model: BoundaryModel, sources: string[]): Promise<CheckResult> {
    const forbidden = buildForbiddenRules(model);
    const result = await cruise(sources, {
      validate: true,
      ruleSet: { forbidden },
      doNotFollow: { path: 'node_modules' },
      tsPreCompilationDeps: true,
    });

    const output =
      typeof result.output === 'string' ? JSON.parse(result.output) : (result.output as any);
    const raw: any[] = output?.summary?.violations ?? [];
    const violations: Violation[] = raw
      .filter((v) => v.rule?.severity === 'error')
      .map((v) => ({ from: v.from, to: v.to, rule: v.rule?.name ?? 'unknown' }));

    // A module whose folder matched no source files enforces nothing — the
    // "green but inert" trap. Surface it so a passing check can't hide it.
    const seen: string[] = (output?.modules ?? []).map((m: any) => String(m.source));
    const warnings: string[] = [];
    for (const mod of model.modules) {
      const prefix = `${mod.folder.replace(/\/+$/, '')}/`;
      if (!seen.some((source) => source.startsWith(prefix))) {
        warnings.push(`module '${mod.title}' maps to '${mod.folder}', which matched 0 source files`);
      }
    }

    return { ok: violations.length === 0, violations, warnings };
  }
}
