import * as dependencyCruiser from 'dependency-cruiser';
import type { EnforcerPort, EnforcerConfig, CheckResult, Violation } from '../../core/ports/ports.js';
import type { BoundaryModel } from '../../core/model/boundary-model.js';

// dependency-cruiser ships CommonJS; reach `cruise` through either interop shape.
const cruise: (
  files: string[],
  options: unknown,
) => Promise<{ output: unknown; exitCode: number }> =
  (dependencyCruiser as any).cruise ?? (dependencyCruiser as any).default?.cruise;

interface PathMatcher {
  path: string;
  pathNot?: string[];
}

interface ForbiddenRule {
  name: string;
  comment: string;
  severity: 'error';
  from: PathMatcher;
  to: PathMatcher;
}

function folderPrefix(folder: string): string {
  return folder.replace(/\/+$/, '');
}

function folderToRegex(folder: string): string {
  const escaped = folderPrefix(folder).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return `^${escaped}/`;
}

/** True if `child` is a folder strictly nested under `parent`. */
function isDescendantFolder(child: string, parent: string): boolean {
  const c = folderPrefix(child);
  const p = folderPrefix(parent);
  return c !== p && c.startsWith(`${p}/`);
}

/**
 * Derives one forbidden rule per (module, disallowed target) pair. A module owns
 * its folder MINUS any mapped descendant folders (which belong to more-specific
 * modules). That containment handling means a parent-level rule never governs a
 * child's files, and a module's own internal imports are never flagged.
 * Dependencies into non-module paths (node_modules, unmapped folders) are left
 * untouched — the architecture only governs edges it drew.
 */
function buildForbiddenRules(model: BoundaryModel): ForbiddenRule[] {
  const allowedTargets = new Map<string, Set<string>>();
  for (const m of model.modules) allowedTargets.set(m.id, new Set([m.id]));
  for (const edge of model.allowed) allowedTargets.get(edge.from)?.add(edge.to);

  // Each module's scope: its folder, carving out any mapped descendant folders.
  const scopeOf = new Map<string, PathMatcher>();
  for (const m of model.modules) {
    const descendants = model.modules
      .filter((other) => isDescendantFolder(other.folder, m.folder))
      .map((other) => folderToRegex(other.folder));
    scopeOf.set(
      m.id,
      descendants.length
        ? { path: folderToRegex(m.folder), pathNot: descendants }
        : { path: folderToRegex(m.folder) },
    );
  }

  const rules: ForbiddenRule[] = [];
  for (const from of model.modules) {
    const allowed = allowedTargets.get(from.id)!;
    for (const to of model.modules) {
      if (allowed.has(to.id)) continue; // self or an explicitly allowed edge
      rules.push({
        name: `boundary:${from.id}->${to.id}`,
        comment: `${from.title} may not depend on ${to.title}`,
        severity: 'error',
        from: scopeOf.get(from.id)!,
        to: scopeOf.get(to.id)!,
      });
    }
  }
  return rules;
}

/** First enforcer adapter: targets dependency-cruiser for TypeScript. */
export class DepCruiserEnforcer implements EnforcerPort {
  render(model: BoundaryModel): EnforcerConfig {
    const forbidden = buildForbiddenRules(model);
    const content = `/** Generated by Boundry from the architecture diagram. Do not edit by hand. */
module.exports = {
  forbidden: ${JSON.stringify(forbidden, null, 2)},
  options: {
    doNotFollow: { path: 'node_modules' },
    tsPreCompilationDeps: true,
  },
};
`;
    return { filename: '.dependency-cruiser.cjs', content };
  }

  async check(model: BoundaryModel, sources: string[]): Promise<CheckResult> {
    const forbidden = buildForbiddenRules(model);
    const result = await cruise(sources, {
      validate: true,
      ruleSet: { forbidden },
      doNotFollow: { path: 'node_modules' },
      tsPreCompilationDeps: true,
    });

    const output =
      typeof result.output === 'string' ? JSON.parse(result.output) : (result.output as any);
    const raw: any[] = output?.summary?.violations ?? [];
    const violations: Violation[] = raw
      .filter((v) => v.rule?.severity === 'error')
      .map((v) => ({ from: v.from, to: v.to, rule: v.rule?.name ?? 'unknown' }));

    // A module whose folder matched no source files enforces nothing — the
    // "green but inert" trap. Surface it so a passing check can't hide it.
    const seen: string[] = (output?.modules ?? []).map((m: any) => String(m.source));
    const warnings: string[] = [];
    for (const mod of model.modules) {
      const prefix = `${mod.folder.replace(/\/+$/, '')}/`;
      if (!seen.some((source) => source.startsWith(prefix))) {
        warnings.push(`module '${mod.title}' maps to '${mod.folder}', which matched 0 source files`);
      }
    }

    return { ok: violations.length === 0, violations, warnings };
  }
}
